import = [
  "~/.config/alacritty/alacritty-theme/themes/iterm.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
# blur = true

[font]
normal.family = "JetBrainsMono NF"

size = 13

